services:
  web:
    build:
      context: ./web/marriagesaver
      target: builder
    ports:
      - '8000:8000'
  chrome:
    build:
      context: scraper
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./app:/app
    shm_size: '2g'
